In [3]:
import pandas as pd
import numpy as np
import os  
import yfinance as yf
from datetime import datetime, timedelta

In [5]:
# 티커 정의

tickers = ['NVDA', 'GOOGL', 'AAPL', 'MSFT', 'AMZN', 'META', 'TSM', 'TSLA', 'AVGO', 'BRK-A']

In [ ]:
start_date = "2015-01-01"# 문자열 야후파이낸스에서
end_date = datetime.now().strftime("%Y-%m-%d")# 현재시간반환
                        # 문자열 포멧 시간변환

In [8]:
datetime.now().strftime("%Y-%m-%d")

'2026-02-06'

In [ ]:
print(f"Fetching data for: {', '.join(tickers)}") #Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'
print(f"Data range: {start_date} to {end_date} (Exclusive)")

Fetching data for: NVDA, GOOGL, AAPL, MSFT, AMZN, META, TSM, TSLA, AVGO, BRK-A
Data range: 2015-01-01 to 2026-02-06 (Exclusive)

In [ ]:
# yfinance를 통해 수정 종가 데이터 다운로드
data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=True)['Close']#수정종가를 가져오기위한 방법
# ['Close']가 없다면 그날의 고점 저점 거래량 종가 가나타남

[*********************100%***********************]  10 of 10 completed

In [ ]:
print(data)# 단위가 다를때만 StandardScaler사용

Ticker            AAPL        AMZN        AVGO     BRK-A       GOOGL  \
Date
2015-01-02   24.237551   15.426000    7.560339  223600.0   26.278946
2015-01-05   23.554743   15.109500    7.439483  220980.0   25.778227
2015-01-06   23.556953   14.764500    7.270282  220450.0   25.142035
2015-01-07   23.887274   14.921000    7.466676  223480.0   25.068092
2015-01-08   24.805077   15.023000    7.839820  226680.0   25.155436
...                ...         ...         ...       ...         ...
2026-01-30  259.480011  239.300003  331.299988  722500.0  338.000000
2026-02-02  270.010010  242.960007  331.109985  729425.0  343.690002
2026-02-03  269.480011  238.619995  320.329987  740150.0  339.709991
2026-02-04  276.489990  232.990005  308.049988  757890.0  333.040009
2026-02-05  275.910004  222.690002  310.510010  756943.0  331.250000

Ticker            META        MSFT        NVDA        TSLA         TSM
Date
2015-01-02   77.905792   39.858463    0.483011   14.620667   16.631805
2015-01-05   76.654549   39.491924    0.474853   14.006000   16.228706
2015-01-06   75.621758   38.912292    0.460456   14.085333   15.945039
2015-01-07   75.621758   39.406685    0.459257   14.063333   16.176455
2015-01-08   77.637680   40.565948    0.476533   14.041333   16.280956
...                ...         ...         ...         ...         ...
2026-01-30  716.500000  430.290009  191.130005  430.410004  330.559998
2026-02-02  706.409973  423.369995  185.610001  421.809998  341.359985
2026-02-03  691.700012  411.209991  180.339996  421.959991  335.750000
2026-02-04  668.989990  414.190002  174.190002  406.010010  325.739990
2026-02-05  670.210022  393.670013  171.880005  397.209991  330.730011

[2790 rows x 10 columns]

In [24]:
# 데이터를 날짜(인덱스) 기준으로 오름차순 정렬 (연-월-일 순)하여 적재 준비
data.sort_index()

Ticker,AAPL,AMZN,AVGO,BRK-A,GOOGL,META,MSFT,NVDA,TSLA,TSM
Date,,,,,,,,,,
2015-01-02,24.237551,15.426000,7.560339,223600.0,26.278946,77.905792,39.858463,0.483011,14.620667,16.631805
2015-01-05,23.554743,15.109500,7.439483,220980.0,25.778227,76.654549,39.491924,0.474853,14.006000,16.228706
2015-01-06,23.556953,14.764500,7.270282,220450.0,25.142035,75.621758,38.912292,0.460456,14.085333,15.945039
2015-01-07,23.887274,14.921000,7.466676,223480.0,25.068092,75.621758,39.406685,0.459257,14.063333,16.176455
2015-01-08,24.805077,15.023000,7.839820,226680.0,25.155436,77.637680,40.565948,0.476533,14.041333,16.280956
...,...,...,...,...,...,...,...,...,...,...
2026-01-30,259.480011,239.300003,331.299988,722500.0,338.000000,716.500000,430.290009,191.130005,430.410004,330.559998
2026-02-02,270.010010,242.960007,331.109985,729425.0,343.690002,706.409973,423.369995,185.610001,421.809998,341.359985
2026-02-03,269.480011,238.619995,320.329987,740150.0,339.709991,691.700012,411.209991,180.339996,421.959991,335.750000
2026-02-04,276.489990,232.990005,308.049988,757890.0,333.040009,668.989990,414.190002,174.190002,406.010010,325.739990
2026-02-05,275.910004,222.690002,310.510010,756943.0,331.250000,670.210022,393.670013,171.880005,397.209991,330.730011

In [25]:
if data.empty:
        print("No data fetched. Please check your internet connection or ticker symbols.")

In [27]:
data.empty

False

In [ ]:
# Display first few rows 탈출자
# 
print("\nFirst 5 rows of fetched data:")
print(data.head())

First 5 rows of fetched data:
Ticker           AAPL     AMZN      AVGO     BRK-A      GOOGL       META  \
Date
2015-01-02  24.237551  15.4260  7.560339  223600.0  26.278946  77.905792
2015-01-05  23.554743  15.1095  7.439483  220980.0  25.778227  76.654549
2015-01-06  23.556953  14.7645  7.270282  220450.0  25.142035  75.621758
2015-01-07  23.887274  14.9210  7.466676  223480.0  25.068092  75.621758
2015-01-08  24.805077  15.0230  7.839820  226680.0  25.155436  77.637680

Ticker           MSFT      NVDA       TSLA        TSM
Date
2015-01-02  39.858463  0.483011  14.620667  16.631805
2015-01-05  39.491924  0.474853  14.006000  16.228706
2015-01-06  38.912292  0.460456  14.085333  15.945039
2015-01-07  39.406685  0.459257  14.063333  16.176455
2015-01-08  40.565948  0.476533  14.041333  16.280956

In [29]:
from stock_db_manager import StockDBManager

In [30]:
print("\nOracle DB에 데이터를 저장을 시작합니다...")
db_manager = StockDBManager()
db_manager.connect()

Oracle DB에 데이터를 저장을 시작합니다...
Oracle DB에 성공적으로 연결되었습니다.
모든 DB 테이블(STOCK_DATA, LOG_RETURNS, STOCK_STATS, EWMA_COVARIANCE)이 준비되었습니다.

In [ ]:
df_long = df.stack().reset_index()
df_long.columns = ['TRADE_DATE', 'TICKER', 'CLOSE_PRICE']

In [31]:
print(data)

Ticker            AAPL        AMZN        AVGO     BRK-A       GOOGL  \
Date
2015-01-02   24.237551   15.426000    7.560339  223600.0   26.278946
2015-01-05   23.554743   15.109500    7.439483  220980.0   25.778227
2015-01-06   23.556953   14.764500    7.270282  220450.0   25.142035
2015-01-07   23.887274   14.921000    7.466676  223480.0   25.068092
2015-01-08   24.805077   15.023000    7.839820  226680.0   25.155436
...                ...         ...         ...       ...         ...
2026-01-30  259.480011  239.300003  331.299988  722500.0  338.000000
2026-02-02  270.010010  242.960007  331.109985  729425.0  343.690002
2026-02-03  269.480011  238.619995  320.329987  740150.0  339.709991
2026-02-04  276.489990  232.990005  308.049988  757890.0  333.040009
2026-02-05  275.910004  222.690002  310.510010  756943.0  331.250000

Ticker            META        MSFT        NVDA        TSLA         TSM
Date
2015-01-02   77.905792   39.858463    0.483011   14.620667   16.631805
2015-01-05   76.654549   39.491924    0.474853   14.006000   16.228706
2015-01-06   75.621758   38.912292    0.460456   14.085333   15.945039
2015-01-07   75.621758   39.406685    0.459257   14.063333   16.176455
2015-01-08   77.637680   40.565948    0.476533   14.041333   16.280956
...                ...         ...         ...         ...         ...
2026-01-30  716.500000  430.290009  191.130005  430.410004  330.559998
2026-02-02  706.409973  423.369995  185.610001  421.809998  341.359985
2026-02-03  691.700012  411.209991  180.339996  421.959991  335.750000
2026-02-04  668.989990  414.190002  174.190002  406.010010  325.739990
2026-02-05  670.210022  393.670013  171.880005  397.209991  330.730011

[2790 rows x 10 columns]

In [ ]:
data.stack().reset_index()
# 세로를 가로로

            Date Ticker              0
0     2015-01-02   AAPL      24.237551
1     2015-01-02   AMZN      15.426000
2     2015-01-02   AVGO       7.560339
3     2015-01-02  BRK-A  223600.000000
4     2015-01-02  GOOGL      26.278946
...          ...    ...            ...
27895 2026-02-05   META     670.210022
27896 2026-02-05   MSFT     393.670013
27897 2026-02-05   NVDA     171.880005
27898 2026-02-05   TSLA     397.209991
27899 2026-02-05    TSM     330.730011

[27900 rows x 3 columns]

In [39]:
df_long = data.stack().reset_index()
df_long.columns = ['TRADE_DATE', 'TICKER', 'CLOSE_PRICE']

# 날짜(TRADE_DATE)와 티커(TICKER) 순으로 엄격하게 오름차순 정렬
df_long = df_long.sort_values(by=['TRADE_DATE', 'TICKER'])

In [40]:
print(df_long)

      TRADE_DATE TICKER    CLOSE_PRICE
0     2015-01-02   AAPL      24.237551
1     2015-01-02   AMZN      15.426000
2     2015-01-02   AVGO       7.560339
3     2015-01-02  BRK-A  223600.000000
4     2015-01-02  GOOGL      26.278946
...          ...    ...            ...
27895 2026-02-05   META     670.210022
27896 2026-02-05   MSFT     393.670013
27897 2026-02-05   NVDA     171.880005
27898 2026-02-05   TSLA     397.209991
27899 2026-02-05    TSM     330.730011

[27900 rows x 3 columns]

In [42]:
print(df_long.iterrows())

<generator object DataFrame.iterrows at 0x0000016DB1DD4370>

In [ ]:
for _, row in df_long.iterrows():
                # datetime -> date 변환 (시간 제거)
                trade_date = row['TRADE_DATE'].to_pydatetime().date()

In [52]:
data_to_insert=[]
for _, row in df_long.iterrows():
                # datetime -> date 변환 (시간 제거)
                # 오라클이 인식하지 못하는 타임스탬프타입을 파이썬 기본 날짜 데이터타입으로 변환
                trade_date = row['TRADE_DATE'].to_pydatetime().date()
                data_to_insert.append((str(row['TICKER']), trade_date, float(row['CLOSE_PRICE'])))

In [54]:
data_to_insert

[('AAPL', datetime.date(2015, 1, 2), 24.237550735473633),
 ('AMZN', datetime.date(2015, 1, 2), 15.425999641418457),
 ('AVGO', datetime.date(2015, 1, 2), 7.560339450836182),
 ('BRK-A', datetime.date(2015, 1, 2), 223600.0),
 ('GOOGL', datetime.date(2015, 1, 2), 26.278945922851562),
 ('META', datetime.date(2015, 1, 2), 77.90579223632812),
 ('MSFT', datetime.date(2015, 1, 2), 39.858463287353516),
 ('NVDA', datetime.date(2015, 1, 2), 0.4830114245414734),
 ('TSLA', datetime.date(2015, 1, 2), 14.620667457580566),
 ('TSM', datetime.date(2015, 1, 2), 16.631805419921875),
 ('AAPL', datetime.date(2015, 1, 5), 23.55474281311035),
 ('AMZN', datetime.date(2015, 1, 5), 15.10949993133545),
 ('AVGO', datetime.date(2015, 1, 5), 7.439483165740967),
 ('BRK-A', datetime.date(2015, 1, 5), 220980.0),
 ('GOOGL', datetime.date(2015, 1, 5), 25.778226852416992),
 ('META', datetime.date(2015, 1, 5), 76.65454864501953),
 ('MSFT', datetime.date(2015, 1, 5), 39.49192428588867),
 ('NVDA', datetime.date(2015, 1, 5), 0.4748532772064209),
 ('TSLA', datetime.date(2015, 1, 5), 14.005999565124512),
 ('TSM', datetime.date(2015, 1, 5), 16.22870635986328),
 ('AAPL', datetime.date(2015, 1, 6), 23.55695343017578),
 ('AMZN', datetime.date(2015, 1, 6), 14.76449966430664),
 ('AVGO', datetime.date(2015, 1, 6), 7.27028226852417),
 ('BRK-A', datetime.date(2015, 1, 6), 220450.0),
 ('GOOGL', datetime.date(2015, 1, 6), 25.14203453063965),
 ('META', datetime.date(2015, 1, 6), 75.62175750732422),
 ('MSFT', datetime.date(2015, 1, 6), 38.91229248046875),
 ('NVDA', datetime.date(2015, 1, 6), 0.4604564607143402),
 ('TSLA', datetime.date(2015, 1, 6), 14.085332870483398),
 ('TSM', datetime.date(2015, 1, 6), 15.945038795471191),
 ('AAPL', datetime.date(2015, 1, 7), 23.88727378845215),
 ('AMZN', datetime.date(2015, 1, 7), 14.920999526977539),
 ('AVGO', datetime.date(2015, 1, 7), 7.466675758361816),
 ('BRK-A', datetime.date(2015, 1, 7), 223480.0),
 ('GOOGL', datetime.date(2015, 1, 7), 25.068092346191406),
 ('META', datetime.date(2015, 1, 7), 75.62175750732422),
 ('MSFT', datetime.date(2015, 1, 7), 39.40668487548828),
 ('NVDA', datetime.date(2015, 1, 7), 0.4592568278312683),
 ('TSLA', datetime.date(2015, 1, 7), 14.063332557678223),
 ('TSM', datetime.date(2015, 1, 7), 16.176454544067383),
 ('AAPL', datetime.date(2015, 1, 8), 24.805076599121094),
 ('AMZN', datetime.date(2015, 1, 8), 15.02299976348877),
 ('AVGO', datetime.date(2015, 1, 8), 7.839820384979248),
 ('BRK-A', datetime.date(2015, 1, 8), 226680.0),
 ('GOOGL', datetime.date(2015, 1, 8), 25.15543556213379),
 ('META', datetime.date(2015, 1, 8), 77.63768005371094),
 ('MSFT', datetime.date(2015, 1, 8), 40.565948486328125),
 ('NVDA', datetime.date(2015, 1, 8), 0.47653278708457947),
 ('TSLA', datetime.date(2015, 1, 8), 14.041333198547363),
 ('TSM', datetime.date(2015, 1, 8), 16.280956268310547),
 ('AAPL', datetime.date(2015, 1, 9), 24.831684112548828),
 ('AMZN', datetime.date(2015, 1, 9), 14.846500396728516),
 ('AVGO', datetime.date(2015, 1, 9), 7.9236650466918945),
 ('BRK-A', datetime.date(2015, 1, 9), 224675.0),
 ('GOOGL', datetime.date(2015, 1, 9), 24.84825325012207),
 ('META', datetime.date(2015, 1, 9), 77.20072937011719),
 ('MSFT', datetime.date(2015, 1, 9), 40.22499465942383),
 ('NVDA', datetime.date(2015, 1, 9), 0.4784524142742157),
 ('TSLA', datetime.date(2015, 1, 9), 13.77733325958252),
 ('TSM', datetime.date(2015, 1, 9), 15.825599670410156),
 ('AAPL', datetime.date(2015, 1, 12), 24.219816207885742),
 ('AMZN', datetime.date(2015, 1, 12), 14.570500373840332),
 ('AVGO', datetime.date(2015, 1, 12), 7.792229175567627),
 ('BRK-A', datetime.date(2015, 1, 12), 222424.0),
 ('GOOGL', datetime.date(2015, 1, 12), 24.6666259765625),
 ('META', datetime.date(2015, 1, 12), 76.18781280517578),
 ('MSFT', datetime.date(2015, 1, 12), 39.72208023071289),
 ('NVDA', datetime.date(2015, 1, 12), 0.4724538028240204),
 ('TSLA', datetime.date(2015, 1, 12), 13.480667114257812),
 ('TSM', datetime.date(2015, 1, 12), 15.519545555114746),
 ('AAPL', datetime.date(2015, 1, 13), 24.434860229492188),
 ('AMZN', datetime.date(2015, 1, 13), 14.737000465393066),
 ('AVGO', datetime.date(2015, 1, 13), 7.748425006866455),
 ('BRK-A', datetime.date(2015, 1, 13), 223000.0),
 ('GOOGL', datetime.date(2015, 1, 13), 24.9018497467041),
 ('META', datetime.date(2015, 1, 13), 75.91966247558594),
 ('MSFT', datetime.date(2015, 1, 13), 39.51749038696289),
 ('NVDA', datetime.date(2015, 1, 13), 0.4717338979244232),
 ('TSLA', datetime.date(2015, 1, 13), 13.616666793823242),
 ('TSM', datetime.date(2015, 1, 13), 15.713628768920898),
 ('AAPL', datetime.date(2015, 1, 14), 24.341747283935547),
 ('AMZN', datetime.date(2015, 1, 14), 14.66349983215332),
 ('AVGO', datetime.date(2015, 1, 14), 7.809602737426758),
 ('BRK-A', datetime.date(2015, 1, 14), 221878.0),
 ('GOOGL', datetime.date(2015, 1, 14), 25.106801986694336),
 ('META', datetime.date(2015, 1, 14), 75.75084686279297),
 ('MSFT', datetime.date(2015, 1, 14), 39.176536560058594),
 ('NVDA', datetime.date(2015, 1, 14), 0.4736534655094147),
 ('TSLA', datetime.date(2015, 1, 14), 12.845999717712402),
 ('TSM', datetime.date(2015, 1, 14), 15.721091270446777),
 ('AAPL', datetime.date(2015, 1, 15), 23.681106567382812),
 ('AMZN', datetime.date(2015, 1, 15), 14.34749984741211),
 ('AVGO', datetime.date(2015, 1, 15), 7.6532464027404785),
 ('BRK-A', datetime.date(2015, 1, 15), 221510.0),
 ('GOOGL', datetime.date(2015, 1, 15), 25.011520385742188),
 ('META', datetime.date(2015, 1, 15), 73.53632354736328),
 ('MSFT', datetime.date(2015, 1, 15), 38.76738739013672),
 ('NVDA', datetime.date(2015, 1, 15), 0.47029435634613037),
 ('TSLA', datetime.date(2015, 1, 15), 12.791333198547363),
 ('TSM', datetime.date(2015, 1, 15), 17.08716583251953),
 ('AAPL', datetime.date(2015, 1, 16), 23.497100830078125),
 ('AMZN', datetime.date(2015, 1, 16), 14.536999702453613),
 ('AVGO', datetime.date(2015, 1, 16), 7.842087268829346),
 ('BRK-A', datetime.date(2015, 1, 16), 223615.0),
 ('GOOGL', datetime.date(2015, 1, 16), 25.331600189208984),
 ('META', datetime.date(2015, 1, 16), 74.65850067138672),
 ('MSFT', datetime.date(2015, 1, 16), 39.41520690917969),
 ('NVDA', datetime.date(2015, 1, 16), 0.47893238067626953),
 ('TSLA', datetime.date(2015, 1, 16), 12.871333122253418),
 ('TSM', datetime.date(2015, 1, 16), 16.870683670043945),
 ('AAPL', datetime.date(2015, 1, 20), 24.102319717407227),
 ('AMZN', datetime.date(2015, 1, 20), 14.472000122070312),
 ('AVGO', datetime.date(2015, 1, 20), 7.9213995933532715),
 ('BRK-A', datetime.date(2015, 1, 20), 222636.0),
 ('GOOGL', datetime.date(2015, 1, 20), 25.305797576904297),
 ('META', datetime.date(2015, 1, 20), 75.71112823486328),
 ('MSFT', datetime.date(2015, 1, 20), 39.54307174682617),
 ('NVDA', datetime.date(2015, 1, 20), 0.48037198185920715),
 ('TSLA', datetime.date(2015, 1, 20), 12.795332908630371),
 ('TSM', datetime.date(2015, 1, 20), 17.236465454101562),
 ('AAPL', datetime.date(2015, 1, 21), 24.286331176757812),
 ('AMZN', datetime.date(2015, 1, 21), 14.862500190734863),
 ('AVGO', datetime.date(2015, 1, 21), 7.959920883178711),
 ('BRK-A', datetime.date(2015, 1, 21), 220895.0),
 ('GOOGL', datetime.date(2015, 1, 21), 25.82438087463379),
 ('META', datetime.date(2015, 1, 21), 76.20765686035156),
 ('MSFT', datetime.date(2015, 1, 21), 39.14242935180664),
 ('NVDA', datetime.date(2015, 1, 21), 0.4870906472206116),
 ('TSLA', datetime.date(2015, 1, 21), 13.104666709899902),
 ('TSM', datetime.date(2015, 1, 21), 17.3260498046875),
 ('AAPL', datetime.date(2015, 1, 22), 24.91814613342285),
 ('AMZN', datetime.date(2015, 1, 22), 15.515999794006348),
 ('AVGO', datetime.date(2015, 1, 22), 7.946325778961182),
 ('BRK-A', datetime.date(2015, 1, 22), 224915.0),
 ('GOOGL', datetime.date(2015, 1, 22), 26.663537979125977),
 ('META', datetime.date(2015, 1, 22), 77.11135864257812),
 ('MSFT', datetime.date(2015, 1, 22), 40.17383575439453),
 ('NVDA', datetime.date(2015, 1, 22), 0.4954887330532074),
 ('TSLA', datetime.date(2015, 1, 22), 13.441332817077637),
 ('TSM', datetime.date(2015, 1, 22), 17.699291229248047),
 ('AAPL', datetime.date(2015, 1, 23), 25.046724319458008),
 ('AMZN', datetime.date(2015, 1, 23), 15.619500160217285),
 ('AVGO', datetime.date(2015, 1, 23), 8.080777168273926),
 ('BRK-A', datetime.date(2015, 1, 23), 223751.0),
 ('GOOGL', datetime.date(2015, 1, 23), 26.89429473876953),
 ('META', datetime.date(2015, 1, 23), 77.29011535644531),
 ('MSFT', datetime.date(2015, 1, 23), 40.216468811035156),
 ('NVDA', datetime.date(2015, 1, 23), 0.49692806601524353),
 ('TSLA', datetime.date(2015, 1, 23), 13.419333457946777),
 ('TSM', datetime.date(2015, 1, 23), 17.90830421447754),
 ('AAPL', datetime.date(2015, 1, 26), 25.07332992553711),
 ('AMZN', datetime.date(2015, 1, 26), 15.482999801635742),
 ('AVGO', datetime.date(2015, 1, 26), 8.061893463134766),
 ('BRK-A', datetime.date(2015, 1, 26), 224184.0),
 ('GOOGL', datetime.date(2015, 1, 26), 26.634756088256836),
 ('META', datetime.date(2015, 1, 26), 76.96239471435547),
 ('MSFT', datetime.date(2015, 1, 26), 40.07156753540039),
 ('NVDA', datetime.date(2015, 1, 26), 0.49476876854896545),
 ('TSLA', datetime.date(2015, 1, 26), 13.770000457763672),
 ('TSM', datetime.date(2015, 1, 26), 18.03520965576172),
 ('AAPL', datetime.date(2015, 1, 27), 24.195436477661133),
 ('AMZN', datetime.date(2015, 1, 27), 15.337499618530273),
 ('AVGO', datetime.date(2015, 1, 27), 7.915355682373047),
 ('BRK-A', datetime.date(2015, 1, 27), 221511.0),
 ('GOOGL', datetime.date(2015, 1, 27), 25.864078521728516),
 ('META', datetime.date(2015, 1, 27), 75.25433349609375),
 ('MSFT', datetime.date(2015, 1, 27), 36.36360168457031),
 ('NVDA', datetime.date(2015, 1, 27), 0.47101420164108276),
 ('TSLA', datetime.date(2015, 1, 27), 13.732000350952148),
 ('TSM', datetime.date(2015, 1, 27), 18.057613372802734),
 ('AAPL', datetime.date(2015, 1, 28), 25.563262939453125),
 ('AMZN', datetime.date(2015, 1, 28), 15.195500373840332),
 ('AVGO', datetime.date(2015, 1, 28), 7.931215286254883),
 ('BRK-A', datetime.date(2015, 1, 28), 217160.0),
 ('GOOGL', datetime.date(2015, 1, 28), 25.42936134338379),
 ('META', datetime.date(2015, 1, 28), 75.71112823486328),
 ('MSFT', datetime.date(2015, 1, 28), 35.110557556152344),
 ('NVDA', datetime.date(2015, 1, 28), 0.463335782289505),
 ('TSLA', datetime.date(2015, 1, 28), 13.291333198547363),
 ('TSM', datetime.date(2015, 1, 28), 17.8635196685791),
 ('AAPL', datetime.date(2015, 1, 29), 26.359140396118164),
 ('AMZN', datetime.date(2015, 1, 29), 15.58899974822998),
 ('AVGO', datetime.date(2015, 1, 29), 8.046788215637207),
 ('BRK-A', datetime.date(2015, 1, 29), 219998.0),
 ('GOOGL', datetime.date(2015, 1, 29), 25.469064712524414),
 ('META', datetime.date(2015, 1, 29), 77.45893096923828),
 ('MSFT', datetime.date(2015, 1, 29), 35.80953598022461),
 ('NVDA', datetime.date(2015, 1, 29), 0.474613219499588),
 ('TSLA', datetime.date(2015, 1, 29), 13.680000305175781),
 ('TSM', datetime.date(2015, 1, 29), 17.385766983032227),
 ('AAPL', datetime.date(2015, 1, 30), 25.9733943939209),
 ('AMZN', datetime.date(2015, 1, 30), 17.726499557495117),
 ('AVGO', datetime.date(2015, 1, 30), 7.771081447601318),
 ('BRK-A', datetime.date(2015, 1, 30), 215865.0),
 ('GOOGL', datetime.date(2015, 1, 30), 26.675947189331055),
 ('META', datetime.date(2015, 1, 30), 75.38343048095703),
 ('MSFT', datetime.date(2015, 1, 30), 34.43716812133789),
 ('NVDA', datetime.date(2015, 1, 30), 0.4606965482234955),
 ('TSLA', datetime.date(2015, 1, 30), 13.573332786560059),
 ('TSM', datetime.date(2015, 1, 30), 16.95280647277832),
 ('AAPL', datetime.date(2015, 2, 2), 26.299280166625977),
 ('AMZN', datetime.date(2015, 2, 2), 18.223499298095703),
 ('AVGO', datetime.date(2015, 2, 2), 7.736335754394531),
 ('BRK-A', datetime.date(2015, 2, 2), 220100.0),
 ('GOOGL', datetime.date(2015, 2, 2), 26.410449981689453),
 ('META', datetime.date(2015, 2, 2), 74.46980285644531),
 ('MSFT', datetime.date(2015, 2, 2), 35.18727111816406),
 ('NVDA', datetime.date(2015, 2, 2), 0.4707741141319275),
 ('TSLA', datetime.date(2015, 2, 2), 14.062666893005371),
 ('TSM', datetime.date(2015, 2, 2), 17.124496459960938),
 ('AAPL', datetime.date(2015, 2, 3), 26.30371856689453),
 ('AMZN', datetime.date(2015, 2, 3), 18.177499771118164),
 ('AVGO', datetime.date(2015, 2, 3), 7.795250415802002),
 ('BRK-A', datetime.date(2015, 2, 3), 222183.0),
 ('GOOGL', datetime.date(2015, 2, 3), 26.465036392211914),
 ('META', datetime.date(2015, 2, 3), 74.87696075439453),
 ('MSFT', datetime.date(2015, 2, 3), 35.46004867553711),
 ('NVDA', datetime.date(2015, 2, 3), 0.48253151774406433),
 ('TSLA', datetime.date(2015, 2, 3), 14.557332992553711),
 ('TSM', datetime.date(2015, 2, 3), 17.281259536743164),
 ('AAPL', datetime.date(2015, 2, 4), 26.505451202392578),
 ('AMZN', datetime.date(2015, 2, 4), 18.237499237060547),
 ('AVGO', datetime.date(2015, 2, 4), 7.916110992431641),
 ('BRK-A', datetime.date(2015, 2, 4), 221027.0),
 ('GOOGL', datetime.date(2015, 2, 4), 26.107736587524414),
 ('META', datetime.date(2015, 2, 4), 75.10535430908203),
 ('MSFT', datetime.date(2015, 2, 4), 35.66461181640625),
 ('NVDA', datetime.date(2015, 2, 4), 0.48373132944107056),
 ('TSLA', datetime.date(2015, 2, 4), 14.569999694824219),
 ('TSM', datetime.date(2015, 2, 4), 17.60224723815918),
 ('AAPL', datetime.date(2015, 2, 5), 26.69464111328125),
 ('AMZN', datetime.date(2015, 2, 5), 18.694499969482422),
 ('AVGO', datetime.date(2015, 2, 5), 8.02186107635498),
 ('BRK-A', datetime.date(2015, 2, 5), 224560.0),
 ('GOOGL', datetime.date(2015, 2, 5), 26.29283905029297),
 ('META', datetime.date(2015, 2, 5), 75.08551025390625),
 ('MSFT', datetime.date(2015, 2, 5), 36.18459701538086),
 ('NVDA', datetime.date(2015, 2, 5), 0.49164944887161255),
 ('TSLA', datetime.date(2015, 2, 5), 14.732666969299316),
 ('TSM', datetime.date(2015, 2, 5), 17.661962509155273),
 ('AAPL', datetime.date(2015, 2, 6), 26.4698486328125),
 ('AMZN', datetime.date(2015, 2, 6), 18.714000701904297),
 ('AVGO', datetime.date(2015, 2, 6), 7.91157865524292),
 ('BRK-A', datetime.date(2015, 2, 6), 224880.0),
 ('GOOGL', datetime.date(2015, 2, 6), 26.493820190429688),
 ('META', datetime.date(2015, 2, 6), 73.95340728759766),
 ('MSFT', datetime.date(2015, 2, 6), 36.15048599243164),
 ('NVDA', datetime.date(2015, 2, 6), 0.4894901216030121),
 ('TSLA', datetime.date(2015, 2, 6), 14.490667343139648),
 ('TSM', datetime.date(2015, 2, 6), 17.24393081665039),
 ('AAPL', datetime.date(2015, 2, 9), 26.645671844482422),
 ('AMZN', datetime.date(2015, 2, 9), 18.527999877929688),
 ('AVGO', datetime.date(2015, 2, 9), 7.722740173339844),
 ('BRK-A', datetime.date(2015, 2, 9), 224000.0),
 ('GOOGL', datetime.date(2015, 2, 9), 26.265544891357422),
 ('META', datetime.date(2015, 2, 9), 73.92362213134766),
 ('MSFT', datetime.date(2015, 2, 9), 36.10787582397461),
 ('NVDA', datetime.date(2015, 2, 9), 0.48901018500328064),
 ('TSLA', datetime.date(2015, 2, 9), 14.498666763305664),
 ('TSM', datetime.date(2015, 2, 9), 16.922948837280273),
 ('AAPL', datetime.date(2015, 2, 10), 27.157573699951172),
 ('AMZN', datetime.date(2015, 2, 10), 18.649999618530273),
 ('AVGO', datetime.date(2015, 2, 10), 8.085308074951172),
 ('BRK-A', datetime.date(2015, 2, 10), 225140.0),
 ('GOOGL', datetime.date(2015, 2, 10), 26.805465698242188),
 ('META', datetime.date(2015, 2, 10), 74.66841888427734),
 ('MSFT', datetime.date(2015, 2, 10), 36.31245422363281),
 ('NVDA', datetime.date(2015, 2, 10), 0.5026870965957642),
 ('TSLA', datetime.date(2015, 2, 10), 14.419333457946777),
 ('TSM', datetime.date(2015, 2, 10), 17.811267852783203),
 ('AAPL', datetime.date(2015, 2, 11), 27.794116973876953),
 ('AMZN', datetime.date(2015, 2, 11), 18.756999969482422),
 ('AVGO', datetime.date(2015, 2, 11), 8.153292655944824),
 ('BRK-A', datetime.date(2015, 2, 11), 224393.0),
 ('GOOGL', datetime.date(2015, 2, 11), 26.698272705078125),
 ('META', datetime.date(2015, 2, 11), 75.97925567626953),
 ('MSFT', datetime.date(2015, 2, 11), 36.12492370605469),
 ('NVDA', datetime.date(2015, 2, 11), 0.49932774901390076),
 ('TSLA', datetime.date(2015, 2, 11), 14.186667442321777),
 ('TSM', datetime.date(2015, 2, 11), 18.132253646850586),
 ('AAPL', datetime.date(2015, 2, 12), 28.145774841308594),
 ('AMZN', datetime.date(2015, 2, 12), 18.85849952697754),
 ('AVGO', datetime.date(2015, 2, 12), 8.286234855651855),
 ('BRK-A', datetime.date(2015, 2, 12), 224460.0),
 ('GOOGL', datetime.date(2015, 2, 12), 27.095773696899414),
 ('META', datetime.date(2015, 2, 12), 75.70121002197266),
 ('MSFT', datetime.date(2015, 2, 12), 36.73012924194336),
 ('NVDA', datetime.date(2015, 2, 12), 0.5350797772407532),
 ('TSLA', datetime.date(2015, 2, 12), 13.525333404541016),
 ('TSM', datetime.date(2015, 2, 12), 18.266624450683594),
 ('AAPL', datetime.date(2015, 2, 13), 28.28376579284668),
 ('AMZN', datetime.date(2015, 2, 13), 19.09149932861328),
 ('AVGO', datetime.date(2015, 2, 13), 8.320221900939941),
 ('BRK-A', datetime.date(2015, 2, 13), 222555.0),
 ('GOOGL', datetime.date(2015, 2, 13), 27.351343154907227),
 ('META', datetime.date(2015, 2, 13), 75.21460723876953),
 ('MSFT', datetime.date(2015, 2, 13), 37.39501190185547),
 ('NVDA', datetime.date(2015, 2, 13), 0.5353196263313293),
 ('TSLA', datetime.date(2015, 2, 13), 13.584667205810547),
 ('TSM', datetime.date(2015, 2, 13), 18.542827606201172),
 ('AAPL', datetime.date(2015, 2, 17), 28.450693130493164),
 ('AMZN', datetime.date(2015, 2, 17), 18.771499633789062),
 ('AVGO', datetime.date(2015, 2, 17), 8.374608039855957),
 ('BRK-A', datetime.date(2015, 2, 17), 223300.0),
 ('GOOGL', datetime.date(2015, 2, 17), 27.046146392822266),
 ('META', datetime.date(2015, 2, 17), 75.07556915283203),
 ('MSFT', datetime.date(2015, 2, 17), 37.412166595458984),
 ('NVDA', datetime.date(2015, 2, 17), 0.536999523639679),
 ('TSLA', datetime.date(2015, 2, 17), 13.623332977294922),
 ('TSM', datetime.date(2015, 2, 17), 18.49057388305664),
 ('AAPL', datetime.date(2015, 2, 18), 28.648778915405273),
 ('AMZN', datetime.date(2015, 2, 18), 18.668500900268555),
 ('AVGO', datetime.date(2015, 2, 18), 8.308892250061035),
 ('BRK-A', datetime.date(2015, 2, 18), 222800.0),
 ('GOOGL', datetime.date(2015, 2, 18), 26.929031372070312),
 ('META', datetime.date(2015, 2, 18), 76.17787170410156),
 ('MSFT', datetime.date(2015, 2, 18), 37.369258880615234),
 ('NVDA', datetime.date(2015, 2, 18), 0.5307607650756836),
 ('TSLA', datetime.date(2015, 2, 18), 13.630666732788086),
 ('TSM', datetime.date(2015, 2, 18), 18.44577980041504),
 ('AAPL', datetime.date(2015, 2, 19), 28.58868408203125),
 ('AMZN', datetime.date(2015, 2, 19), 18.950000762939453),
 ('AVGO', datetime.date(2015, 2, 19), 8.376876831054688),
 ('BRK-A', datetime.date(2015, 2, 19), 221495.0),
 ('GOOGL', datetime.date(2015, 2, 19), 27.11760711669922),
 ('META', datetime.date(2015, 2, 19), 78.86907196044922),
 ('MSFT', datetime.date(2015, 2, 19), 37.34348678588867),
 ('NVDA', datetime.date(2015, 2, 19), 0.532200276851654),
 ('TSLA', datetime.date(2015, 2, 19), 14.11400032043457),
 ('TSM', datetime.date(2015, 2, 19), 18.303951263427734),
 ('AAPL', datetime.date(2015, 2, 20), 28.822372436523438),
 ('AMZN', datetime.date(2015, 2, 20), 19.183000564575195),
 ('AVGO', datetime.date(2015, 2, 20), 8.464498519897461),
 ('BRK-A', datetime.date(2015, 2, 20), 223100.0),
 ('GOOGL', datetime.date(2015, 2, 20), 26.88684844970703),
 ('META', datetime.date(2015, 2, 20), 79.34574127197266),
 ('MSFT', datetime.date(2015, 2, 20), 37.65255355834961),
 ('NVDA', datetime.date(2015, 2, 20), 0.536039412021637),
 ('TSLA', datetime.date(2015, 2, 20), 14.473999977111816),
 ('TSM', datetime.date(2015, 2, 20), 18.244230270385742),
 ('AAPL', datetime.date(2015, 2, 23), 29.601364135742188),
 ('AMZN', datetime.date(2015, 2, 23), 19.006999969482422),
 ('AVGO', datetime.date(2015, 2, 23), 8.52417278289795),
 ('BRK-A', datetime.date(2015, 2, 23), 221000.0),
 ('GOOGL', datetime.date(2015, 2, 23), 26.549400329589844),
 ('META', datetime.date(2015, 2, 23), 78.29308319091797),
 ('MSFT', datetime.date(2015, 2, 23), 37.901512145996094),
 ('NVDA', datetime.date(2015, 2, 23), 0.5317203402519226),

In [55]:
if data_to_insert:
    # 최종 확인차 리스트에서도 날짜순 정렬 수행
    data_to_insert.sort(key=lambda x: (x[1], x[0]))

In [56]:
data_to_insert

[('AAPL', datetime.date(2015, 1, 2), 24.237550735473633),
 ('AMZN', datetime.date(2015, 1, 2), 15.425999641418457),
 ('AVGO', datetime.date(2015, 1, 2), 7.560339450836182),
 ('BRK-A', datetime.date(2015, 1, 2), 223600.0),
 ('GOOGL', datetime.date(2015, 1, 2), 26.278945922851562),
 ('META', datetime.date(2015, 1, 2), 77.90579223632812),
 ('MSFT', datetime.date(2015, 1, 2), 39.858463287353516),
 ('NVDA', datetime.date(2015, 1, 2), 0.4830114245414734),
 ('TSLA', datetime.date(2015, 1, 2), 14.620667457580566),
 ('TSM', datetime.date(2015, 1, 2), 16.631805419921875),
 ('AAPL', datetime.date(2015, 1, 5), 23.55474281311035),
 ('AMZN', datetime.date(2015, 1, 5), 15.10949993133545),
 ('AVGO', datetime.date(2015, 1, 5), 7.439483165740967),
 ('BRK-A', datetime.date(2015, 1, 5), 220980.0),
 ('GOOGL', datetime.date(2015, 1, 5), 25.778226852416992),
 ('META', datetime.date(2015, 1, 5), 76.65454864501953),
 ('MSFT', datetime.date(2015, 1, 5), 39.49192428588867),
 ('NVDA', datetime.date(2015, 1, 5), 0.4748532772064209),
 ('TSLA', datetime.date(2015, 1, 5), 14.005999565124512),
 ('TSM', datetime.date(2015, 1, 5), 16.22870635986328),
 ('AAPL', datetime.date(2015, 1, 6), 23.55695343017578),
 ('AMZN', datetime.date(2015, 1, 6), 14.76449966430664),
 ('AVGO', datetime.date(2015, 1, 6), 7.27028226852417),
 ('BRK-A', datetime.date(2015, 1, 6), 220450.0),
 ('GOOGL', datetime.date(2015, 1, 6), 25.14203453063965),
 ('META', datetime.date(2015, 1, 6), 75.62175750732422),
 ('MSFT', datetime.date(2015, 1, 6), 38.91229248046875),
 ('NVDA', datetime.date(2015, 1, 6), 0.4604564607143402),
 ('TSLA', datetime.date(2015, 1, 6), 14.085332870483398),
 ('TSM', datetime.date(2015, 1, 6), 15.945038795471191),
 ('AAPL', datetime.date(2015, 1, 7), 23.88727378845215),
 ('AMZN', datetime.date(2015, 1, 7), 14.920999526977539),
 ('AVGO', datetime.date(2015, 1, 7), 7.466675758361816),
 ('BRK-A', datetime.date(2015, 1, 7), 223480.0),
 ('GOOGL', datetime.date(2015, 1, 7), 25.068092346191406),
 ('META', datetime.date(2015, 1, 7), 75.62175750732422),
 ('MSFT', datetime.date(2015, 1, 7), 39.40668487548828),
 ('NVDA', datetime.date(2015, 1, 7), 0.4592568278312683),
 ('TSLA', datetime.date(2015, 1, 7), 14.063332557678223),
 ('TSM', datetime.date(2015, 1, 7), 16.176454544067383),
 ('AAPL', datetime.date(2015, 1, 8), 24.805076599121094),
 ('AMZN', datetime.date(2015, 1, 8), 15.02299976348877),
 ('AVGO', datetime.date(2015, 1, 8), 7.839820384979248),
 ('BRK-A', datetime.date(2015, 1, 8), 226680.0),
 ('GOOGL', datetime.date(2015, 1, 8), 25.15543556213379),
 ('META', datetime.date(2015, 1, 8), 77.63768005371094),
 ('MSFT', datetime.date(2015, 1, 8), 40.565948486328125),
 ('NVDA', datetime.date(2015, 1, 8), 0.47653278708457947),
 ('TSLA', datetime.date(2015, 1, 8), 14.041333198547363),
 ('TSM', datetime.date(2015, 1, 8), 16.280956268310547),
 ('AAPL', datetime.date(2015, 1, 9), 24.831684112548828),
 ('AMZN', datetime.date(2015, 1, 9), 14.846500396728516),
 ('AVGO', datetime.date(2015, 1, 9), 7.9236650466918945),
 ('BRK-A', datetime.date(2015, 1, 9), 224675.0),
 ('GOOGL', datetime.date(2015, 1, 9), 24.84825325012207),
 ('META', datetime.date(2015, 1, 9), 77.20072937011719),
 ('MSFT', datetime.date(2015, 1, 9), 40.22499465942383),
 ('NVDA', datetime.date(2015, 1, 9), 0.4784524142742157),
 ('TSLA', datetime.date(2015, 1, 9), 13.77733325958252),
 ('TSM', datetime.date(2015, 1, 9), 15.825599670410156),
 ('AAPL', datetime.date(2015, 1, 12), 24.219816207885742),
 ('AMZN', datetime.date(2015, 1, 12), 14.570500373840332),
 ('AVGO', datetime.date(2015, 1, 12), 7.792229175567627),
 ('BRK-A', datetime.date(2015, 1, 12), 222424.0),
 ('GOOGL', datetime.date(2015, 1, 12), 24.6666259765625),
 ('META', datetime.date(2015, 1, 12), 76.18781280517578),
 ('MSFT', datetime.date(2015, 1, 12), 39.72208023071289),
 ('NVDA', datetime.date(2015, 1, 12), 0.4724538028240204),
 ('TSLA', datetime.date(2015, 1, 12), 13.480667114257812),
 ('TSM', datetime.date(2015, 1, 12), 15.519545555114746),
 ('AAPL', datetime.date(2015, 1, 13), 24.434860229492188),
 ('AMZN', datetime.date(2015, 1, 13), 14.737000465393066),
 ('AVGO', datetime.date(2015, 1, 13), 7.748425006866455),
 ('BRK-A', datetime.date(2015, 1, 13), 223000.0),
 ('GOOGL', datetime.date(2015, 1, 13), 24.9018497467041),
 ('META', datetime.date(2015, 1, 13), 75.91966247558594),
 ('MSFT', datetime.date(2015, 1, 13), 39.51749038696289),
 ('NVDA', datetime.date(2015, 1, 13), 0.4717338979244232),
 ('TSLA', datetime.date(2015, 1, 13), 13.616666793823242),
 ('TSM', datetime.date(2015, 1, 13), 15.713628768920898),
 ('AAPL', datetime.date(2015, 1, 14), 24.341747283935547),
 ('AMZN', datetime.date(2015, 1, 14), 14.66349983215332),
 ('AVGO', datetime.date(2015, 1, 14), 7.809602737426758),
 ('BRK-A', datetime.date(2015, 1, 14), 221878.0),
 ('GOOGL', datetime.date(2015, 1, 14), 25.106801986694336),
 ('META', datetime.date(2015, 1, 14), 75.75084686279297),
 ('MSFT', datetime.date(2015, 1, 14), 39.176536560058594),
 ('NVDA', datetime.date(2015, 1, 14), 0.4736534655094147),
 ('TSLA', datetime.date(2015, 1, 14), 12.845999717712402),
 ('TSM', datetime.date(2015, 1, 14), 15.721091270446777),
 ('AAPL', datetime.date(2015, 1, 15), 23.681106567382812),
 ('AMZN', datetime.date(2015, 1, 15), 14.34749984741211),
 ('AVGO', datetime.date(2015, 1, 15), 7.6532464027404785),
 ('BRK-A', datetime.date(2015, 1, 15), 221510.0),
 ('GOOGL', datetime.date(2015, 1, 15), 25.011520385742188),
 ('META', datetime.date(2015, 1, 15), 73.53632354736328),
 ('MSFT', datetime.date(2015, 1, 15), 38.76738739013672),
 ('NVDA', datetime.date(2015, 1, 15), 0.47029435634613037),
 ('TSLA', datetime.date(2015, 1, 15), 12.791333198547363),
 ('TSM', datetime.date(2015, 1, 15), 17.08716583251953),
 ('AAPL', datetime.date(2015, 1, 16), 23.497100830078125),
 ('AMZN', datetime.date(2015, 1, 16), 14.536999702453613),
 ('AVGO', datetime.date(2015, 1, 16), 7.842087268829346),
 ('BRK-A', datetime.date(2015, 1, 16), 223615.0),
 ('GOOGL', datetime.date(2015, 1, 16), 25.331600189208984),
 ('META', datetime.date(2015, 1, 16), 74.65850067138672),
 ('MSFT', datetime.date(2015, 1, 16), 39.41520690917969),
 ('NVDA', datetime.date(2015, 1, 16), 0.47893238067626953),
 ('TSLA', datetime.date(2015, 1, 16), 12.871333122253418),
 ('TSM', datetime.date(2015, 1, 16), 16.870683670043945),
 ('AAPL', datetime.date(2015, 1, 20), 24.102319717407227),
 ('AMZN', datetime.date(2015, 1, 20), 14.472000122070312),
 ('AVGO', datetime.date(2015, 1, 20), 7.9213995933532715),
 ('BRK-A', datetime.date(2015, 1, 20), 222636.0),
 ('GOOGL', datetime.date(2015, 1, 20), 25.305797576904297),
 ('META', datetime.date(2015, 1, 20), 75.71112823486328),
 ('MSFT', datetime.date(2015, 1, 20), 39.54307174682617),
 ('NVDA', datetime.date(2015, 1, 20), 0.48037198185920715),
 ('TSLA', datetime.date(2015, 1, 20), 12.795332908630371),
 ('TSM', datetime.date(2015, 1, 20), 17.236465454101562),
 ('AAPL', datetime.date(2015, 1, 21), 24.286331176757812),
 ('AMZN', datetime.date(2015, 1, 21), 14.862500190734863),
 ('AVGO', datetime.date(2015, 1, 21), 7.959920883178711),
 ('BRK-A', datetime.date(2015, 1, 21), 220895.0),
 ('GOOGL', datetime.date(2015, 1, 21), 25.82438087463379),
 ('META', datetime.date(2015, 1, 21), 76.20765686035156),
 ('MSFT', datetime.date(2015, 1, 21), 39.14242935180664),
 ('NVDA', datetime.date(2015, 1, 21), 0.4870906472206116),
 ('TSLA', datetime.date(2015, 1, 21), 13.104666709899902),
 ('TSM', datetime.date(2015, 1, 21), 17.3260498046875),
 ('AAPL', datetime.date(2015, 1, 22), 24.91814613342285),
 ('AMZN', datetime.date(2015, 1, 22), 15.515999794006348),
 ('AVGO', datetime.date(2015, 1, 22), 7.946325778961182),
 ('BRK-A', datetime.date(2015, 1, 22), 224915.0),
 ('GOOGL', datetime.date(2015, 1, 22), 26.663537979125977),
 ('META', datetime.date(2015, 1, 22), 77.11135864257812),
 ('MSFT', datetime.date(2015, 1, 22), 40.17383575439453),
 ('NVDA', datetime.date(2015, 1, 22), 0.4954887330532074),
 ('TSLA', datetime.date(2015, 1, 22), 13.441332817077637),
 ('TSM', datetime.date(2015, 1, 22), 17.699291229248047),
 ('AAPL', datetime.date(2015, 1, 23), 25.046724319458008),
 ('AMZN', datetime.date(2015, 1, 23), 15.619500160217285),
 ('AVGO', datetime.date(2015, 1, 23), 8.080777168273926),
 ('BRK-A', datetime.date(2015, 1, 23), 223751.0),
 ('GOOGL', datetime.date(2015, 1, 23), 26.89429473876953),
 ('META', datetime.date(2015, 1, 23), 77.29011535644531),
 ('MSFT', datetime.date(2015, 1, 23), 40.216468811035156),
 ('NVDA', datetime.date(2015, 1, 23), 0.49692806601524353),
 ('TSLA', datetime.date(2015, 1, 23), 13.419333457946777),
 ('TSM', datetime.date(2015, 1, 23), 17.90830421447754),
 ('AAPL', datetime.date(2015, 1, 26), 25.07332992553711),
 ('AMZN', datetime.date(2015, 1, 26), 15.482999801635742),
 ('AVGO', datetime.date(2015, 1, 26), 8.061893463134766),
 ('BRK-A', datetime.date(2015, 1, 26), 224184.0),
 ('GOOGL', datetime.date(2015, 1, 26), 26.634756088256836),
 ('META', datetime.date(2015, 1, 26), 76.96239471435547),
 ('MSFT', datetime.date(2015, 1, 26), 40.07156753540039),
 ('NVDA', datetime.date(2015, 1, 26), 0.49476876854896545),
 ('TSLA', datetime.date(2015, 1, 26), 13.770000457763672),
 ('TSM', datetime.date(2015, 1, 26), 18.03520965576172),
 ('AAPL', datetime.date(2015, 1, 27), 24.195436477661133),
 ('AMZN', datetime.date(2015, 1, 27), 15.337499618530273),
 ('AVGO', datetime.date(2015, 1, 27), 7.915355682373047),
 ('BRK-A', datetime.date(2015, 1, 27), 221511.0),
 ('GOOGL', datetime.date(2015, 1, 27), 25.864078521728516),
 ('META', datetime.date(2015, 1, 27), 75.25433349609375),
 ('MSFT', datetime.date(2015, 1, 27), 36.36360168457031),
 ('NVDA', datetime.date(2015, 1, 27), 0.47101420164108276),
 ('TSLA', datetime.date(2015, 1, 27), 13.732000350952148),
 ('TSM', datetime.date(2015, 1, 27), 18.057613372802734),
 ('AAPL', datetime.date(2015, 1, 28), 25.563262939453125),
 ('AMZN', datetime.date(2015, 1, 28), 15.195500373840332),
 ('AVGO', datetime.date(2015, 1, 28), 7.931215286254883),
 ('BRK-A', datetime.date(2015, 1, 28), 217160.0),
 ('GOOGL', datetime.date(2015, 1, 28), 25.42936134338379),
 ('META', datetime.date(2015, 1, 28), 75.71112823486328),
 ('MSFT', datetime.date(2015, 1, 28), 35.110557556152344),
 ('NVDA', datetime.date(2015, 1, 28), 0.463335782289505),
 ('TSLA', datetime.date(2015, 1, 28), 13.291333198547363),
 ('TSM', datetime.date(2015, 1, 28), 17.8635196685791),
 ('AAPL', datetime.date(2015, 1, 29), 26.359140396118164),
 ('AMZN', datetime.date(2015, 1, 29), 15.58899974822998),
 ('AVGO', datetime.date(2015, 1, 29), 8.046788215637207),
 ('BRK-A', datetime.date(2015, 1, 29), 219998.0),
 ('GOOGL', datetime.date(2015, 1, 29), 25.469064712524414),
 ('META', datetime.date(2015, 1, 29), 77.45893096923828),
 ('MSFT', datetime.date(2015, 1, 29), 35.80953598022461),
 ('NVDA', datetime.date(2015, 1, 29), 0.474613219499588),
 ('TSLA', datetime.date(2015, 1, 29), 13.680000305175781),
 ('TSM', datetime.date(2015, 1, 29), 17.385766983032227),
 ('AAPL', datetime.date(2015, 1, 30), 25.9733943939209),
 ('AMZN', datetime.date(2015, 1, 30), 17.726499557495117),
 ('AVGO', datetime.date(2015, 1, 30), 7.771081447601318),
 ('BRK-A', datetime.date(2015, 1, 30), 215865.0),
 ('GOOGL', datetime.date(2015, 1, 30), 26.675947189331055),
 ('META', datetime.date(2015, 1, 30), 75.38343048095703),
 ('MSFT', datetime.date(2015, 1, 30), 34.43716812133789),
 ('NVDA', datetime.date(2015, 1, 30), 0.4606965482234955),
 ('TSLA', datetime.date(2015, 1, 30), 13.573332786560059),
 ('TSM', datetime.date(2015, 1, 30), 16.95280647277832),
 ('AAPL', datetime.date(2015, 2, 2), 26.299280166625977),
 ('AMZN', datetime.date(2015, 2, 2), 18.223499298095703),
 ('AVGO', datetime.date(2015, 2, 2), 7.736335754394531),
 ('BRK-A', datetime.date(2015, 2, 2), 220100.0),
 ('GOOGL', datetime.date(2015, 2, 2), 26.410449981689453),
 ('META', datetime.date(2015, 2, 2), 74.46980285644531),
 ('MSFT', datetime.date(2015, 2, 2), 35.18727111816406),
 ('NVDA', datetime.date(2015, 2, 2), 0.4707741141319275),
 ('TSLA', datetime.date(2015, 2, 2), 14.062666893005371),
 ('TSM', datetime.date(2015, 2, 2), 17.124496459960938),
 ('AAPL', datetime.date(2015, 2, 3), 26.30371856689453),
 ('AMZN', datetime.date(2015, 2, 3), 18.177499771118164),
 ('AVGO', datetime.date(2015, 2, 3), 7.795250415802002),
 ('BRK-A', datetime.date(2015, 2, 3), 222183.0),
 ('GOOGL', datetime.date(2015, 2, 3), 26.465036392211914),
 ('META', datetime.date(2015, 2, 3), 74.87696075439453),
 ('MSFT', datetime.date(2015, 2, 3), 35.46004867553711),
 ('NVDA', datetime.date(2015, 2, 3), 0.48253151774406433),
 ('TSLA', datetime.date(2015, 2, 3), 14.557332992553711),
 ('TSM', datetime.date(2015, 2, 3), 17.281259536743164),
 ('AAPL', datetime.date(2015, 2, 4), 26.505451202392578),
 ('AMZN', datetime.date(2015, 2, 4), 18.237499237060547),
 ('AVGO', datetime.date(2015, 2, 4), 7.916110992431641),
 ('BRK-A', datetime.date(2015, 2, 4), 221027.0),
 ('GOOGL', datetime.date(2015, 2, 4), 26.107736587524414),
 ('META', datetime.date(2015, 2, 4), 75.10535430908203),
 ('MSFT', datetime.date(2015, 2, 4), 35.66461181640625),
 ('NVDA', datetime.date(2015, 2, 4), 0.48373132944107056),
 ('TSLA', datetime.date(2015, 2, 4), 14.569999694824219),
 ('TSM', datetime.date(2015, 2, 4), 17.60224723815918),
 ('AAPL', datetime.date(2015, 2, 5), 26.69464111328125),
 ('AMZN', datetime.date(2015, 2, 5), 18.694499969482422),
 ('AVGO', datetime.date(2015, 2, 5), 8.02186107635498),
 ('BRK-A', datetime.date(2015, 2, 5), 224560.0),
 ('GOOGL', datetime.date(2015, 2, 5), 26.29283905029297),
 ('META', datetime.date(2015, 2, 5), 75.08551025390625),
 ('MSFT', datetime.date(2015, 2, 5), 36.18459701538086),
 ('NVDA', datetime.date(2015, 2, 5), 0.49164944887161255),
 ('TSLA', datetime.date(2015, 2, 5), 14.732666969299316),
 ('TSM', datetime.date(2015, 2, 5), 17.661962509155273),
 ('AAPL', datetime.date(2015, 2, 6), 26.4698486328125),
 ('AMZN', datetime.date(2015, 2, 6), 18.714000701904297),
 ('AVGO', datetime.date(2015, 2, 6), 7.91157865524292),
 ('BRK-A', datetime.date(2015, 2, 6), 224880.0),
 ('GOOGL', datetime.date(2015, 2, 6), 26.493820190429688),
 ('META', datetime.date(2015, 2, 6), 73.95340728759766),
 ('MSFT', datetime.date(2015, 2, 6), 36.15048599243164),
 ('NVDA', datetime.date(2015, 2, 6), 0.4894901216030121),
 ('TSLA', datetime.date(2015, 2, 6), 14.490667343139648),
 ('TSM', datetime.date(2015, 2, 6), 17.24393081665039),
 ('AAPL', datetime.date(2015, 2, 9), 26.645671844482422),
 ('AMZN', datetime.date(2015, 2, 9), 18.527999877929688),
 ('AVGO', datetime.date(2015, 2, 9), 7.722740173339844),
 ('BRK-A', datetime.date(2015, 2, 9), 224000.0),
 ('GOOGL', datetime.date(2015, 2, 9), 26.265544891357422),
 ('META', datetime.date(2015, 2, 9), 73.92362213134766),
 ('MSFT', datetime.date(2015, 2, 9), 36.10787582397461),
 ('NVDA', datetime.date(2015, 2, 9), 0.48901018500328064),
 ('TSLA', datetime.date(2015, 2, 9), 14.498666763305664),
 ('TSM', datetime.date(2015, 2, 9), 16.922948837280273),
 ('AAPL', datetime.date(2015, 2, 10), 27.157573699951172),
 ('AMZN', datetime.date(2015, 2, 10), 18.649999618530273),
 ('AVGO', datetime.date(2015, 2, 10), 8.085308074951172),
 ('BRK-A', datetime.date(2015, 2, 10), 225140.0),
 ('GOOGL', datetime.date(2015, 2, 10), 26.805465698242188),
 ('META', datetime.date(2015, 2, 10), 74.66841888427734),
 ('MSFT', datetime.date(2015, 2, 10), 36.31245422363281),
 ('NVDA', datetime.date(2015, 2, 10), 0.5026870965957642),
 ('TSLA', datetime.date(2015, 2, 10), 14.419333457946777),
 ('TSM', datetime.date(2015, 2, 10), 17.811267852783203),
 ('AAPL', datetime.date(2015, 2, 11), 27.794116973876953),
 ('AMZN', datetime.date(2015, 2, 11), 18.756999969482422),
 ('AVGO', datetime.date(2015, 2, 11), 8.153292655944824),
 ('BRK-A', datetime.date(2015, 2, 11), 224393.0),
 ('GOOGL', datetime.date(2015, 2, 11), 26.698272705078125),
 ('META', datetime.date(2015, 2, 11), 75.97925567626953),
 ('MSFT', datetime.date(2015, 2, 11), 36.12492370605469),
 ('NVDA', datetime.date(2015, 2, 11), 0.49932774901390076),
 ('TSLA', datetime.date(2015, 2, 11), 14.186667442321777),
 ('TSM', datetime.date(2015, 2, 11), 18.132253646850586),
 ('AAPL', datetime.date(2015, 2, 12), 28.145774841308594),
 ('AMZN', datetime.date(2015, 2, 12), 18.85849952697754),
 ('AVGO', datetime.date(2015, 2, 12), 8.286234855651855),
 ('BRK-A', datetime.date(2015, 2, 12), 224460.0),
 ('GOOGL', datetime.date(2015, 2, 12), 27.095773696899414),
 ('META', datetime.date(2015, 2, 12), 75.70121002197266),
 ('MSFT', datetime.date(2015, 2, 12), 36.73012924194336),
 ('NVDA', datetime.date(2015, 2, 12), 0.5350797772407532),
 ('TSLA', datetime.date(2015, 2, 12), 13.525333404541016),
 ('TSM', datetime.date(2015, 2, 12), 18.266624450683594),
 ('AAPL', datetime.date(2015, 2, 13), 28.28376579284668),
 ('AMZN', datetime.date(2015, 2, 13), 19.09149932861328),
 ('AVGO', datetime.date(2015, 2, 13), 8.320221900939941),
 ('BRK-A', datetime.date(2015, 2, 13), 222555.0),
 ('GOOGL', datetime.date(2015, 2, 13), 27.351343154907227),
 ('META', datetime.date(2015, 2, 13), 75.21460723876953),
 ('MSFT', datetime.date(2015, 2, 13), 37.39501190185547),
 ('NVDA', datetime.date(2015, 2, 13), 0.5353196263313293),
 ('TSLA', datetime.date(2015, 2, 13), 13.584667205810547),
 ('TSM', datetime.date(2015, 2, 13), 18.542827606201172),
 ('AAPL', datetime.date(2015, 2, 17), 28.450693130493164),
 ('AMZN', datetime.date(2015, 2, 17), 18.771499633789062),
 ('AVGO', datetime.date(2015, 2, 17), 8.374608039855957),
 ('BRK-A', datetime.date(2015, 2, 17), 223300.0),
 ('GOOGL', datetime.date(2015, 2, 17), 27.046146392822266),
 ('META', datetime.date(2015, 2, 17), 75.07556915283203),
 ('MSFT', datetime.date(2015, 2, 17), 37.412166595458984),
 ('NVDA', datetime.date(2015, 2, 17), 0.536999523639679),
 ('TSLA', datetime.date(2015, 2, 17), 13.623332977294922),
 ('TSM', datetime.date(2015, 2, 17), 18.49057388305664),
 ('AAPL', datetime.date(2015, 2, 18), 28.648778915405273),
 ('AMZN', datetime.date(2015, 2, 18), 18.668500900268555),
 ('AVGO', datetime.date(2015, 2, 18), 8.308892250061035),
 ('BRK-A', datetime.date(2015, 2, 18), 222800.0),
 ('GOOGL', datetime.date(2015, 2, 18), 26.929031372070312),
 ('META', datetime.date(2015, 2, 18), 76.17787170410156),
 ('MSFT', datetime.date(2015, 2, 18), 37.369258880615234),
 ('NVDA', datetime.date(2015, 2, 18), 0.5307607650756836),
 ('TSLA', datetime.date(2015, 2, 18), 13.630666732788086),
 ('TSM', datetime.date(2015, 2, 18), 18.44577980041504),
 ('AAPL', datetime.date(2015, 2, 19), 28.58868408203125),
 ('AMZN', datetime.date(2015, 2, 19), 18.950000762939453),
 ('AVGO', datetime.date(2015, 2, 19), 8.376876831054688),
 ('BRK-A', datetime.date(2015, 2, 19), 221495.0),
 ('GOOGL', datetime.date(2015, 2, 19), 27.11760711669922),
 ('META', datetime.date(2015, 2, 19), 78.86907196044922),
 ('MSFT', datetime.date(2015, 2, 19), 37.34348678588867),
 ('NVDA', datetime.date(2015, 2, 19), 0.532200276851654),
 ('TSLA', datetime.date(2015, 2, 19), 14.11400032043457),
 ('TSM', datetime.date(2015, 2, 19), 18.303951263427734),
 ('AAPL', datetime.date(2015, 2, 20), 28.822372436523438),
 ('AMZN', datetime.date(2015, 2, 20), 19.183000564575195),
 ('AVGO', datetime.date(2015, 2, 20), 8.464498519897461),
 ('BRK-A', datetime.date(2015, 2, 20), 223100.0),
 ('GOOGL', datetime.date(2015, 2, 20), 26.88684844970703),
 ('META', datetime.date(2015, 2, 20), 79.34574127197266),
 ('MSFT', datetime.date(2015, 2, 20), 37.65255355834961),
 ('NVDA', datetime.date(2015, 2, 20), 0.536039412021637),
 ('TSLA', datetime.date(2015, 2, 20), 14.473999977111816),
 ('TSM', datetime.date(2015, 2, 20), 18.244230270385742),
 ('AAPL', datetime.date(2015, 2, 23), 29.601364135742188),
 ('AMZN', datetime.date(2015, 2, 23), 19.006999969482422),
 ('AVGO', datetime.date(2015, 2, 23), 8.52417278289795),
 ('BRK-A', datetime.date(2015, 2, 23), 221000.0),
 ('GOOGL', datetime.date(2015, 2, 23), 26.549400329589844),
 ('META', datetime.date(2015, 2, 23), 78.29308319091797),
 ('MSFT', datetime.date(2015, 2, 23), 37.901512145996094),
 ('NVDA', datetime.date(2015, 2, 23), 0.5317203402519226),